@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

###

GET https://denis.dev.releaseband.com/?player_id=200 HTTP/1.1
# GET /?player_id=200 HTTP/1.1
# Host: {{host}}
Content-Type: {{contentType}}

###

POST /integration.v1.IntegrationService/GetBalance HTTP/1.1
Host: {{hostname}}:8081
Content-Type: {{contentType}}

{
    "player_id": "123"
}
