@remote = https://denis.dev.releaseband.com
@hostname = localhost
@contentType = application/json

###

# @name launch
POST /launch HTTP/1.1
Host: {{hostname}}:8080
Content-Type: {{contentType}}

{
    "playerId": "player",
    "gameId": "game"
}

###

@token = {{launch.response.body.token}}

# # @name init
POST {{remote}}/init HTTP/1.1
# POST /init HTTP/1.1
# Host: {{hostname}}:8081
Content-Type: {{contentType}}

{
    "token": "{{token}}"
}

###

# @name balance
POST /integration.v1.IntegrationService/GetBalance HTTP/1.1
Host: {{hostname}}:8081
Content-Type: {{contentType}}

{
    "player_id": "123"
}
