@remote = https://denis.dev.releaseband.com

###
# @name launch
POST /launch HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "playerId": "player",
    "gameId": "game"
}

###
@token = {{launch.response.body.token}}

# @name init
POST {{remote}}/init HTTP/1.1
Content-Type: application/json

{
    "token": "{{token}}"
}

###
# @name balance
POST /integration.v1.IntegrationService/GetBalance HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "player_id": "123"
}

###
# @name http
POST {{remote}}/http HTTP/1.1
Content-Type: application/json

###
# @name grpc
POST {{remote}}/grpc HTTP/1.1
Content-Type: application/json

###
# @name test
POST /http HTTP/1.1
Host: localhost:6000
Content-Type: application/json
traceparent: 00-58f774820d1130301d91423693afc257-f8a45c3285e07fef-01
