apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: denis
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://tempo-distributor.tempo.svc.cluster.local:9411/api/v2/spans"