kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: denis
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    dapr.io/enabled: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        dapr.io/enabled: "true"
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "gateway"
        dapr.io/app-protocol: "http"
        dapr.io/app-port: "7000"
        dapr.io/config: "main"
        dapr.io/sidecar-listen-addresses: "0.0.0.0"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-app-health-check: "true"
    spec:
      containers:
        - name: gateway
          image: ghcr.io/shumkovdenis/bl:main
          env:
            - name: SERVICE_NAME
              value: "gateway"
            - name: MODE
              value: "http"
            - name: PORT
              value: "7000"
            - name: CALLEE_SERVICE_NAME
              value: "service-a"
            - name: CALLEE_MODE
              value: "grpc"
          ports:
            - containerPort: 7000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          # livenessProbe:
          #   httpGet:
          #     path: v1.0/healthz
          #     port: 3500
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds : 5
          #   failureThreshold : 3
          # readinessProbe:
          #   httpGet:
          #     path: v1.0/healthz
          #     port: 3500
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds : 5
          #   failureThreshold: 3
