name: build

on:
  push:
    branches:
      - "main"
    paths:
      - "services/gateway/**"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/gateway
          push: true
          # context: "{{defaultContext}}:services/gateway"
          tags: ghcr.io/shumkovdenis/bl-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
