name: build remote

on:
  push:
    branches:
      - "main"
    paths:
      - "services/remote/**"
  workflow_dispatch:

env:
  SERVICE_NAME: remote

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker build
        uses: ./.github/actions/build
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}-${{ env.SERVICE_NAME }}
          context: ./services/${{ env.SERVICE_NAME }}
